apiVersion: v1
kind: cypress
defaults: {}
showConsoleLog: false
sauce:
  region: eu-central-1
  concurrency: 2
  sauceignore: .sauceignore
cypress:
  configFile: cypress.config.js
  version: 10.7.0
  record: false
  key: ""
  reporters: []
suites:
- name: cypress - windows 11 - chrome
  browser: chrome
  platformName: windows 11
  config:
    testingType: e2e
    specPattern:
    - '**/*.*'
  mode: sauce
rootDir: .
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: ./artifacts
